"""Create a baseline migrations

Revision ID: b2849aa8ecd2
Revises: e6b176555b5a
Create Date: 2024-09-10 18:00:01.122807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2849aa8ecd2'
down_revision: Union[str, None] = 'e6b176555b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
